# Generated by Django 5.2.7 on 2025-10-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_task_updated_at_alter_task_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='resend_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('concluida', 'Concluída')], default='pendente', max_length=10),
        ),
    ]
