# Generated by Django 5.1.1 on 2025-10-24 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_remove_task_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverificationcode',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at']},
        ),
    ]
